---
deployment:
  tasks:
    - export DEPLOYPATH=repositories/ambassadorswellnesscenter.com/index.html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp Readme.txt $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R forms $DEPLOYPATH
