---
deployment:
  tasks:
    - export DEPLOYMENT_DIR=repositories/ambassadorswellnesscenter/public_html
    - /bin/mkdir -p $DEPLOYMENT_DIR
    - /bin/cp -r * $DEPLOYMENT_DIR/
    - /bin/find $DEPLOYMENT_DIR -type d -exec chmod 755 {} +
    - /bin/find $DEPLOYMENT_DIR -type f -exec chmod 644 {} +
